### ISSUE TITLE
运行完数据没有同步？

### ISSUE THREAD

**Issue by liaoxuewei** [bbossgroups/db-db-job#1]
配置好数据，运行Application，看到日志提示也成功同步，为什么apm的batchtest1没有数据？还少了什么吗？

**Comment by liaoxuewei** [comment]
Parallel batch import Complete tasks:1,Total success import 9 records,Ignore Total 0 records,failed total 0 records.

**Comment by liaoxuewei** [comment]
把INSERT/UPDATE脚本里面的表名batchtest1 改成 batchtest12，一样正常执行，说明根本没有执行脚本？

**Comment by yin-bp** [comment]
> 配置好数据，运行Application，看到日志提示也成功同步，为什么apm的batchtest1没有数据？还少了什么吗？

运行的是哪个作业类，如果是Db2DBdemoWithStatusConfigDB，则需要将datarefactor方法中相关的代码段注释一下再试试：

```java
if(s.incrementAndGet() % 2 == 1) {
					context.markRecoredInsert();
				}
				else if(s.incrementAndGet() % 2 == 0){
					context.markRecoredUpdate();
				}
				else{
					context.markRecoredDelete();
				}
```

这段代码随机将插入的记录删除或者修改掉了

**Comment by yin-bp** [comment]
> 把INSERT/UPDATE脚本里面的表名batchtest1 改成 batchtest12，一样正常执行，说明根本没有执行脚本？

脚本肯定是运行了的，否则你看不到运行结果，可能是你运行的同步删除数据的的作业，所以数据都被删除了

**Comment by liaoxuewei** [comment]
> > 配置好数据，运行Application，看到日志提示也成功同步，为什么apm的batchtest1没有数据？还少了什么吗？
> 
> 运行的是哪个作业类，如果是Db2DBdemoWithStatusConfigDB，则需要将datarefactor方法中相关的代码段注释一下再试试：
> 
> ```java
> if(s.incrementAndGet() % 2 == 1) {
> 					context.markRecoredInsert();
> 				}
> 				else if(s.incrementAndGet() % 2 == 0){
> 					context.markRecoredUpdate();
> 				}
> 				else{
> 					context.markRecoredDelete();
> 				}
> ```
> 
> 这段代码随机将插入的记录删除或者修改掉了

则个注释已经可以了，为什么随机会全部没有呢？

**Comment by liaoxuewei** [comment]
> > 把INSERT/UPDATE脚本里面的表名batchtest1 改成 batchtest12，一样正常执行，说明根本没有执行脚本？
> 
> 脚本肯定是运行了的，否则你看不到运行结果，可能是你运行的同步删除数据的的作业，所以数据都被删除了

不是的，脚本没有运行，我刚刚按上面代码注释掉，再改INSERT INTO batchtest12就会出错了

**Comment by liaoxuewei** [comment]
Db2DBdemo/Db2DBdemoSQL/Db2DBdemoWithStatusConfigDB三个测试类，是怎么控制用哪个，我好像没有找到切换的方式

**Comment by yin-bp** [comment]
> Db2DBdemo/Db2DBdemoSQL/Db2DBdemoWithStatusConfigDB三个测试类，是怎么控制用哪个，我好像没有找到切换的方式

三个demo同时只运行一个，通过demo中afterPropertiesSet方法代码来控制运行哪一个

以下会执行同步
```java

	@Override
	public void afterPropertiesSet() throws Exception {
		this.scheduleImportData();  
	}
```

以下不会执行同步
```java

	@Override
	public void afterPropertiesSet() throws Exception {
		//this.scheduleImportData();   注释后就不会运行了
	}
```

想运行哪个就打开，其他注释掉就行了

**Comment by liaoxuewei** [comment]
OK，谢谢！
